Sir 2010
ValeriiVKovalenko/wallet-bot pull request #23
Opened 2023-06-03 16:22 UTC by ValeriiVKovalenko

2023-06-03 20:57 UTC, AleksandrZholud requested changes
Not ok

2023-06-03 20:57 UTC, AleksandrZholud commented on src/main/java/telegrambot/controller/CardController.java
> +    public String changeCardName(@PathVariable Long id,
Лучше перенести часть имени в основной контроллер. Типа основной /card, а дальше уже допустим /{id}

2023-06-03 20:57 UTC, AleksandrZholud commented on src/main/java/telegrambot/controller/CardController.java
> +
Name лучше передать не как pathVariable, а как body

2023-06-03 20:57 UTC, AleksandrZholud commented on src/main/java/telegrambot/controller/CardController.java
> +    }
Эту всю логику нужно вынести из контроллера в сервис (создать в сервисе метод updateNameById)

2023-06-03 23:55 UTC, AleksandrZholud commented on src/main/java/telegrambot/controller/CardController.java
> +    @PostMapping("/change_card_name/{id}/{newName}")
Лучше перенести часть имени в основной контроллер. Типа основной /card, а дальше уже допустим /{id}

2023-06-03 23:57 UTC, AleksandrZholud commented on src/main/java/telegrambot/controller/CardController.java
> +
Лучше перенести часть имени в основной контроллер. Типа основной /card, а дальше уже допустим /{id}

2023-06-05 10:42 UTC, ValeriiVKovalenko commented on src/main/java/telegrambot/controller/CardController.java
> +
а для body, нужно отдельно создавать класс? и если да, то в какой папке его хранить?

2023-06-17 07:31 UTC, AleksandrZholud requested changes

2023-06-17 07:31 UTC, AleksandrZholud commented on src/main/java/telegrambot/controller/CardController.java
> +    @PostMapping(value = "/{id}")
Why did u use POST mapping?

2023-06-19 22:31 UTC, AleksandrZholud approved these changes
пока что ок, но нужно дождаться мерджа

2023-06-20 19:22 UTC, merged